# Generated by Django 3.0.6 on 2020-05-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='account',
        ),
    ]
