# Generated by Django 3.0.6 on 2020-05-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200512_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
