# Generated by Django 3.0.6 on 2020-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
